create table public."Assignments" (
  id bigint generated by default as identity not null,
  course bigint not null,
  due_date timestamp with time zone null,
  description text null,
  name text not null,
  constraint Assignments_pkey primary key (id),
  constraint Assignments_course_fkey foreign KEY (course) references "Courses" (cid)
) TABLESPACE pg_default;