create table public."Courses" (
  primary_instructor uuid not null default auth.uid (),
  cid bigint generated by default as identity not null,
  start_date date not null,
  end_date date null,
  name text null,
  constraint Courses_pkey primary key (cid),
  constraint Courses_join_code_key unique (join_code),
  constraint Courses_primary_instructor_fkey foreign KEY (primary_instructor) references auth.users (id) on update CASCADE on delete RESTRICT
) TABLESPACE pg_default;